name: web_app_db-dev

services:
  app:
    image: web_app_db:dev
    build: .
    entrypoint: ["fastapi", "dev", "--host", "0.0.0.0", "main.py"]
    environment:
      - DATABASE_URL=postgresql+psycopg://user:password@db:5432/app
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          initial_sync: true
        - action: restart
          path: requirements.txt

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db_network

volumes:
  db_data:

networks:
  db_network:
